### ISSUE TITLE
[Feature Request]: Customize ticket and deal tags

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#256]
### Feature Request

We recently started utilizing Hubspot's tagging feature to help categorize and sort tickets and deals in our various pipelines. We would like to ensure that custom tagging automations are being utilized in all pipelines where they would be useful. The current pipelines we would like to activate this feature for are:

- [ ] Support Pipeline

### Is this request related to a problem?

Pipelines can quickly become overwhelming, the hope is that this tagging system will help our pipelines stay organized and cut down on time spent sorting through various stages and deals/tickets. 

### Use Case

We recently set up this feature in our internal support pipeline to differentiate between CRM Maintenance tickets and GTFS Data Quality tickets. This feature has been well-received and we would like to do something similar in our external Support Pipeline, as well as any other pipelines that tagging would benefit. 

### Additional Info

n/a

**Comment by laneymangan** [comment]
@o-ram would deal tagging be useful for the Payments Pipeline? If so, any thoughts on the specific tags we would like to create?

**Comment by laneymangan** [comment]
Support Pipeline tagging ideas
(@o-ram feel free to add to this list)

- [ ] Scheduling tag

**Comment by o-ram** [comment]
Payments pipeline ideas:
(@laneymangan please feel free to add to this! I went with regular bullet points instead of a checkmark list because these ideas are a _lot_ less formulated and very rough brainstorming)

- Something with latest status property?
- Something with Felix property?
- Something related to names - in-state vs. out of state, district number
- "critical"
- TAP/Clipper designations?
- something related to certain period of time of inaction? (like a stale deal)

Shown in the Thursday AM meeting to those who were there until the end, Erika to think through any ideas she has and share them with Laney and/or Olivia.

**Comment by laneymangan** [comment]
@o-ram (CC @AnthonyRollins) bad news.....apparently we're limited to 10 tags per object...ugh (excuse me while I submit a Hubspot suggestion...) 
![image](https://github.com/cal-itp/customer-success/assets/107429473/b2e7bb0d-5328-4f34-8aff-028f531fda40)

So since this is per object, we can only have 10 between the Internal Support PP and Support PP. As it is now, we had 12 tag ideas, so we're not too far off but that wouldn't allow for any additional tags, even in the internal support (I believe we were leaving that open as a possibility for more workflows there)

 A few thoughts:
- I can forgo a "scheduling" tag and keep a scheduling stage
- forgo the FYI tag with the understanding that if there's no tag, no action was needed
- if we need to pare down even more, we can try to think of the tags as broader buckets and group some of the subjects together (not sure atm what those buckets would be..)

Any thoughts?

**Comment by thekaveman** [comment]
Chiming in from my far off point of view:

> forgo the FYI tag with the understanding that if there's no tag, no action was needed

This seems like a reasonable change to make.

Disappointing that the product has a limit on tags though!

**Comment by o-ram** [comment]
ugh, bummer! @laneymangan let us know if there is anything we can upvote 😏 

Cutting the FYI tag and keeping the routed to scheduling column also sounds fine to me - as long as you're alright with keeping the scheduling column, as it mostly impacts your workflow. Agree with establishing the understanding that no tag means no action needed. 

That does put us right at 10, but I think that will be alright. We can use these tags for the internal support pipeline as well for any future workflows that come in there - the general categories should still apply and if it turns out we need something more specific as well, we can always add more to the ticket creation form.

**Comment by o-ram** [comment]
ah, except we also wanted some type of "long term effort" tag that I was just about to make an issue for.

What if we cut the `CCJPA` tag? We get next to nothing for that, and as long as we associate the company with the ticket, we can still easily filter and pull some numbers related to them if asked.

**Comment by laneymangan** [comment]
All ticket tags have been created and conditional triggers activated. Final list of tags:

Internal Support
1.CRM Maintenance
2.GTFS Data Quality

Support 
3. Payments
4. GTFS Data
5. Benefits
6. Product Scheduler
7. Connectivity
8. Payments Data
9. On Hold

All pipelines
10. Long Term Effort (see ticket #269 for context)

two last thoughts if we need to free up space now or in the future: 
-  We might be able to repurpose the `GTFS Data Quality` tag for Internal Support in place of the `GTFS Data` tag for Support, if removing "Quality" from the internal support workflow won't cause any confusion (or vice versa, if using "GTFS Data Quality" for the support pipeline won't cause confusion)
- `On Hold` might not be entirely necessary, although I do see a usecase (I'm using it currently on a ticket in fact) but it might be possible to use `Long Term Effort` in place of it if we need to (if something is on hold, its taking longer than usual which might technically make it a "long term effort"...)

( @o-ram )

**Comment by laneymangan** [comment]
Feature Request for deal tagging related to the payments pipeline has been moved to ticket #271

**Comment by AnthonyRollins** [comment]
@o-ram I am just catching up here; I can reach out to our sales agent / Customer support to see if this feature costs a lot to add more on or if it is something else.

**Comment by AnthonyRollins** [comment]
@o-ram Following up: I talked to support and they said this feature doesn't exist to increase, but there is a [community post ](https://community.hubspot.com/t5/HubSpot-Ideas/Tags-for-deals/idi-p/788382) about this that we can upvote
