### ISSUE TITLE
Audit users/permissions in HubSpot

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/customer-success#273]

**Comment by AnthonyRollins** [comment]
@thekaveman We took a look at a lot of things in our last CRM audit, including [user permissions](https://docs.google.com/spreadsheets/d/1RvvKmHigOplWY6sOumPkpK0xzg7Ez8U8Z2x2FoNR_OU/edit#gid=310378033) I went through and updated users and deactivated those that no longer need access, but I haven't done it since a few months ago no.

**Comment by thekaveman** [comment]
Great, thanks @AnthonyRollins! This was an old ticket originally from a list of items I had on https://github.com/cal-itp/services-team/issues/25, but if you've done it recently I think we can consider this closed.
