### ISSUE TITLE
Create a new issue template for cohort addition requests

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#274]
A need has been identified to have a formal place where the larger Cal-ITP team can request that an agency be added to the Account Manager cohort as it grows. The decision was made to have an issue template that people can fill out so there is one go-to place that is tracked/documented. 

This template should include the following questions:

1. What is the name of the agency?
2. Why do you believe they should be added? (this is just to get a bit of background, not to accept or deny anybody)
3. Who currently communicates with this agency?

The template should also clarify that we want every agency to have an AM, but we are capacity limited. Submitting this form does not guarantee we can add somebody at that present moment, but we will do our best.

**Comment by AnthonyRollins** [comment]
Other questions we can ask: 

1. Do you know if there will be increased communication with this agent in the future?
2. What contacts from this agency should we be in touch with? 
3. Additional commnents?

**Comment by o-ram** [comment]
@laneymangan here is a [SOP/training guide](https://docs.google.com/document/d/1TxpzTHkLkZZFIprZta2aELpNAwKfvRrc7yVICpjaELw/edit) for editing an existing template or creating a new one. Should guide you through the steps you need to take. Let me know if you need any help or have any questions!

**Comment by laneymangan** [comment]
@o-ram let me know how [this](https://github.com/cal-itp/customer-success/issues/new?assignees=&labels=feature&projects=&template=cohort-request.yml&title=%5BCohort+Request%5D%3A+) looks / if I should make any edits. 

Question: under "what contacts should we be in touch with?" should I add a description to not include email addresses?

**Comment by AnthonyRollins** [comment]
A few things to note with pull requests and issue templates:
- When creating a new branch, we should use a naming structure that is similar to Milestones; for instance, instead of `laneymangan-patch-1`, we should describe what the branch is for `template/cohort-request` so looking back at branches, we know why they were created. Additional details about those branches can be added to the pull request. I should have mentioned this is past branches and pull requests, but we should update the SOP guide to reflect this.
- For this pull request, there are several different options to build out your questions, so the questions that don't require a great deal of text to answer could use [input type](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#input) instead of a text-area type.

I know I haven't been very involved with this, but I did want to point out those two things for future issue templates and pull requests.

**Comment by laneymangan** [comment]
@AnthonyRollins Noted! Thanks, I updated a few of the questions to `input` and updated the SOP (@o-ram I will tag you to "sign off" on the SOP so as not to over-step in your doc)

**Comment by o-ram** [comment]
Thanks @laneymangan, all looks good to me! I flagged one other place in the SOP doc we should probably update to be consistent, so let's figure that out within the Gdoc.

**Comment by laneymangan** [comment]
[Cohort request form](https://github.com/cal-itp/customer-success/issues/new?assignees=&labels=cohort&projects=&template=cohort-request.yml&title=%5BCohort+Request%5D%3A+) has been created, label "Cohort" has been created and will automatically be assigned when a form is submitted.

**Comment by AnthonyRollins** [comment]
@laneymangan Labels are case-sensitive, so in the code you have  
```
labels:
  - "cohort"
``` 
and the label you created used a capital C - `Cohort`. I went ahead an edited the label to lowercase. Let me know if you have any questions.

**Comment by laneymangan** [comment]
@AnthonyRollins thank you! noticed it wasn't working but wasn't sure why--mystery solved, thanks!
