### ISSUE TITLE
AM SOPs for connectivity workstream

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#277]
As part of the "menu of services", Account Managers will take on some of the duties within the connectivity workstream, for which documentation is needed.

- [x] Connectivity campaign (see #275) ahead of March 2024 deadline
- [ ] SOPs for Promoting the existence of data plans, Outreach, educating, supporting agencies in purchase process, handing off to connectivity subject matter experts in the near-term
~- [ ] Creation of external marketing materials (resourcing on this TBD)~

**Comment by o-ram** [comment]
- Campaign guide is complete and outreach will pick up week of 7/31
- Near term SOPs (during campaign/while SME's have hours to spend on helping CS team out and knowledge sharing) in progress. SOPs beyond that will be developed as this process goes on and the connectivity experts slowly transfer more of the work on to AMs
- CS and connectivity teams connecting biweekly

**Comment by laneymangan** [comment]
Looks great! I made a couple small suggestions

**Comment by laneymangan** [comment]
https://docs.google.com/document/d/1f9z5WM9ZszLiQtlsJxWkgn_FyiFtrIz7MxfgXhDyUkA/edit

- [ ] Meet with Laurens and Jacquelyn 8/30
- [ ] Finalize SOP
- [ ] Olivia to approve SOP after OOO

**Comment by laneymangan** [comment]
@o-ram [This is ready for your review](https://docs.google.com/document/d/1f9z5WM9ZszLiQtlsJxWkgn_FyiFtrIz7MxfgXhDyUkA/edit#heading=h.2xzb0r6ihpk1), whenever you get a chance! I met with the Laurens and Jacquelyn last Wednesday and cleared up a few of my questions. My notes from the meeting are below in case you want to take a look. 

- We do not need to CC Lauren and Jacquelyn until the agency has replied to the initial outreach attempt. We all agreed this will make it a bit easier for their inboxes, and we have the tracking spreadsheet that they can reference for who has been reached out to
- an FAQ is being worked on so that we can answer more detailed questions, but for now, its perfectly fine to loop in Lauren and Jacquelyn when questions are asked by agencies
- We can offer a meeting once the agency expresses interest, to help speed things along and thoroughly answer questions, however....
      - We no longer offer demos (ie "try before you buy") Only in worst case scenarios. 
      - Soon, we will have a "self-service" page on the website, which we can direct agencies to. This will hopefully help eliminate the need of some meetings, but meetings with agencies will always be an option to better support them
- We can share the one-pager at the conferences, but we will need to update it to include the self-service information. We can check back in on this closer to conference time.

**Comment by laneymangan** [comment]
working session scheduled for 12/6

**Comment by laneymangan** [comment]
[Connectivity SOP can be found here](https://docs.google.com/document/d/1f9z5WM9ZszLiQtlsJxWkgn_FyiFtrIz7MxfgXhDyUkA/edit). Once the Cellular Provider property is created, and the Connectivity Pipeline is archived, the SOP will need to be updated. I have added a task to the property issue ( #384 ) to track this task so this issue can be closed.
