### ISSUE TITLE
Create a list of agencies for support letters

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#375]
Build a list of agencies we can contact to sign support letters.

**Comment by o-ram** [comment]
First pass at a [list of agencies](https://docs.google.com/document/d/1ImXpJwdyotzHbJ8-JHRkGhujLWDtX_jy48cf8xLYrKE/edit ) who might do _something_ to publicly voice support for Cal-ITP. To be shared with DoH.

**Comment by AnthonyRollins** [comment]
I believe you shared this with DoH and other, do you think we can close this out?

**Comment by o-ram** [comment]
@AnthonyRollins yes, thanks for closing! With the holidays, I don't think I ever ended up actually sharing it with DoH, but in the comms monthly meeting, we all agreed that since the governor's proposed budget came out, the urgency on this seems to have died down, and there are no plans of pursuing it right now. This also lives on the drive so whenever it's useful, I can flag it to folks and edit it. In general, there is still an appetite for gathering testimonials and agency support, but we have time to think about that with more care and open more specific issues as needed.
