### ISSUE TITLE
Create a new my map for Cal-ITP reach

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#520]
Create a [new map](https://www.google.com/maps/d/u/0/edit?mid=1g8lKkk6i1LtbkYQnWT_XS-FWlCYN9a4&ll=38.17717246294404,-121.29072007616452&z=6) that does not show Tiers A-E but showcases whether agencies are using a product with Cal-ITP. 

Current thought on segmentation for all 189 agencies would be: 
- Using contactless payments and benefits
- Using contactless payments
- In progress with Payments
- No implementation

In the future, we should also include something for GTFS data quality

**Comment by AnthonyRollins** [comment]
@o-ram I know of all the agencies with Cal-ITP services using the work done in #405, but I wanted to make sure I still should be looking at [CS Tier list spreadsheet](https://docs.google.com/spreadsheets/d/1qWzuW07Tbq05ww6p9iMGPUZ5d4eqkbwS/edit?gid=901052190#gid=901052190) for an accurate list of the tiers? I know the tiers are updated in Hubspot; would that be the most precise list? Also, is it safe to assume agencies in the `D` and up have communicated with us before?

**Comment by o-ram** [comment]
I would go to Hubspot for the most precise list. AFAIK we haven't changed anybody's tier since the last import of the spreadsheet data into hubspot, but since there has been some scenario planning happening on/off and a lot more people in that spreadsheet, I can't be sure. Hubspot, I feel very sure is accurate.

Yes, it is safe to assume D & up have communicated with us at least once.

**Comment by AnthonyRollins** [comment]
@o-ram I updated [the map](https://www.google.com/maps/d/u/0/edit?mid=1g8lKkk6i1LtbkYQnWT_XS-FWlCYN9a4&ll=36.66784203490761,-119.69198109285401&z=7) with some details I could find around Hubspot and the Cal-ITP services spreadsheet. Let me know what changes I should make or if there are transit agencies I am missing.

**Comment by o-ram** [comment]
I made some updates to the map based on the most up-to-date satus of our "reach". A few notes:

- The only agencies completely missing from the list are City of Wasco and QC Metrolink, both of whom are payments in progress agencies. The latter is out of state, but I noticed we included the South Carolina agency, so maybe we want them too?
- What about when an agency is in progress with payments but also received GTFS assistance from us? Do we want to somehow note that?
- This map is only meant to include the "big 3" right now, correct? Meaning no ODS, MDIP, etc?
- The AM's listed within the cards are wrong for most of them, not sure why. 
- Some of the cities like Auburn and Ripon are mapping to cities with those same names in other states rather than the city in CA

**Comment by AnthonyRollins** [comment]
A few responses to your comments/questions:
- I will add City of Wasco and Metrolink. What is "QC" Metrolink, is it this [agency](https://www.metroqc.com/)? I can also look into the other agencies.
- I am trying to decided if that provides more value, as of now, my thinking has been that Benefits and Payments is the bigger combo of things than GTFS. But is there a big list that we should highlight in this way? 
- As of right now, the big thing has more standing with the leadership audience but we can adjust as we improve the map
- Yeah I just need to delete all of those from the old map. They don't really need to say any of that info to the audience who is going to use this map.
- I will adjust those places.

**Comment by o-ram** [comment]
Thanks! 

- Yes, you had the right agency for QC Metrolink - I added them in while making my edits :) 
- There were some other out of state agencies in the pipeline that I added to the map since they seem to excite people
- Fine with me to just cover the main 3 and keep just the Benefits/Payments combo. We can always expand later down the road if it makes sense
- I slightly expanded the GTFS marker to extend beyond data creation so it also applies to agencies in which we got their feed into trip planners or took on some other major level of technical assistance effort with them. I felt like anything that took a decent amount of time on our end is fair to capture here. Let me know if you want to chat about that further though.

With all of that, the map is as accurate as it can be right now from my POV. Everything looks in the right place and statuses are accurate based on our criteria. Of course, the map will always be a bit "in motion" since agencies are actively working on things, but this is current for the foreseeable future.
